[package]
name = "unixstring"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bstr      = "0.2.17"
thiserror = "1.0.29"
bytecount = "0.6.2"
libc      = "0.2.103"